/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/table.glb --transform --keepnames 
Files: public/models/table.glb [14.64MB] > C:\Users\jashw\Desktop\jashtechno-next\table-transformed.glb [241.46KB] (98%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/table-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Table_Table_0" geometry={nodes.Table_Table_0.geometry} material={materials.Table} scale={0.224} />
    </group>
  )
}

useGLTF.preload('/table-transformed.glb')
